# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

#Notes
#user name for VMs is created as vagrant

#<vagrant box add bento/ubuntu-24.04> to add OS image to internal repository
#<vagrant up> to start VMs (run at the same folder where this file is, or pass file as argument)
#<vagrant halt> to stop VMs
#<vagrant destroy> to remove VMs

#Variables
PUBLIC_KEY_PATH = "~/.ssh/id_ed25519.pub" 
PRIVATE_KEY_PATH = "~/.ssh/id_ed25519"  

READ_PUBLIC_KEY = File.read(File.expand_path(PUBLIC_KEY_PATH)).strip

# My VM
MY_VM_IP  = "192.168.56.10"  

# Control Plane VM
CONTROL_PLANE_IP  = "192.168.56.100"  

# Nodes VMs
Number_Nodes = 2 #number Node VMs to launch
NODES_IP_RANGE= "192.168.56" #Change me if needed!

# Monitor VM
MONITOR_VM_IP = "192.168.56.200" #Change me if needed!


Vagrant.configure("2") do |config|

  # Global configurations
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  
  # Use libvirt provider instead of VirtualBox
  config.vm.provider :libvirt do |lv|
    lv.memory = 1024
    lv.cpus = 2
  end
  config.vm.provision :shell, privileged: true, inline: $provision_all

  # Nodes VMs configuration
  (1..Number_Nodes).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network :private_network, ip: "#{NODES_IP_RANGE}.#{100+i}"
    end
  end

  # Myvm configuration
  config.vm.define :myvm do |mv|
    mv.vm.hostname = "myvm"
    mv.vm.network :private_network, ip: MY_VM_IP
    mv.vm.provision :file, source: PRIVATE_KEY_PATH, destination: "~/.ssh/"
    mv.vm.provision :shell, inline: $provision_myvm
  end

  # Control Plane VM configuration
  config.vm.define :controlplane do |cp|
    cp.vm.hostname = "controlPlane"
    cp.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    cp.vm.network :private_network, ip: CONTROL_PLANE_IP
  end

  # Monitor VM configuration
  config.vm.define :monitor do |monitor|
    monitor.vm.hostname = "monitor"
    monitor.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    monitor.vm.network :private_network, ip: MONITOR_VM_IP
  end

end

# Provisioning scripts
$provision_all = <<-SHELL
  echo "[ALL|Task 1] Configure SSH Public Key authentication"
  echo "#{READ_PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys
  sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
  sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  systemctl restart ssh.service
  apt update -y
SHELL

$provision_myvm = <<-SHELL
  echo "[myvm|Task 1] Install Ansible"
  apt upgrade
  apt -y install software-properties-common
  apt-add-repository -y ppa:ansible/ansible
  apt install ansible -y
SHELL
