apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # Generic type for arbitrary user-defined data (key-value pairs)
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==