
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INT ISBN TEXTOBiblio : LivrosLivros : LivroLivros : Livros LivroLivro  : Titulo Autor Ano ISBN '.'Titulo : TEXTOAutor  : TEXTOAno    : INT"
    
_lr_action_items = {'TEXTO':([0,2,3,4,5,6,12,],[5,5,-2,8,-5,-3,-4,]),'$end':([1,2,3,6,12,],[0,-1,-2,-3,-4,]),'INT':([7,8,],[10,-6,]),'ISBN':([9,10,],[11,-7,]),'.':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Biblio':([0,],[1,]),'Livros':([0,],[2,]),'Livro':([0,2,],[3,6,]),'Titulo':([0,2,],[4,4,]),'Autor':([4,],[7,]),'Ano':([7,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Biblio","S'",1,None,None,None),
  ('Biblio -> Livros','Biblio',1,'p_biblio','biblio_yacc_1.py',20),
  ('Livros -> Livro','Livros',1,'p_livros1','biblio_yacc_1.py',26),
  ('Livros -> Livros Livro','Livros',2,'p_livros2','biblio_yacc_1.py',30),
  ('Livro -> Titulo Autor Ano ISBN .','Livro',5,'p_livro','biblio_yacc_1.py',34),
  ('Titulo -> TEXTO','Titulo',1,'p_titulo','biblio_yacc_1.py',39),
  ('Autor -> TEXTO','Autor',1,'p_autor','biblio_yacc_1.py',42),
  ('Ano -> INT','Ano',1,'p_ano','biblio_yacc_1.py',47),
]
