-- succ 8
-- > 9
-- min 9 8
-- > 8
-- max 9 8
-- > 9
-- maximum [1,2,9,10]
-- > 10
-- We can use the let keyword to define a name right in GHCI. Doing let a = 1 inside GHCI is the equivalent of writing a = 1 in a script and then loading it.
-- If you want to get an element out of a list by index, use !!
-- "Steve Buscemi" !! 6
-- > 'B'
------------------------------------------------------------------------------------------------------------


-- head -> takes a list and returns its head
-- tail -> takes a list and returns its tail
-- last -> takes a list and returns its last element.
-- init -> takes a list and returns everything except its last element.
-- length -> takes a list and returns its length, obviously.
-- null -> checks if a list is empty
-- reverse -> reverses a list.
-- take -> takes number and a list
-- drop -> works in a similar way, only it drops the number of elements from the beginning of a list.
-- sum --> takes a list of numbers and returns their sum.
-- product -> takes a list of numbers and returns their product.
-- elem -> takes a thing and a list of things and tells us if that thing is an element of the list.
-- 